version: 2
project_name: tmgc

builds:
  - id: tmgc
    main: ./cmd/tmgc
    binary: tmgc
    ldflags:
      - -s -w -X main.version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: tmgc
    ids:
      - tmgc
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true

release:
  mode: keep-existing
